model: # joint optimizing for ae and mlp, each cls 1 mlp, max_min normalization
  class_name: diff_nerf.ae_kl_3d_3.AutoencoderKL
  embed_dim: 6
  std_scale: 3.5
  use_render_loss: False
  use_cls_loss: False
  cls_start: 10000
  cls_path:
  render_start: 20000
  maxm: 191.3546
  minm: -258.9259
  lossconfig:
    disc_start: 80001
    kl_weight: 0.000001
    disc_weight: 0.5
    perceptual_weight: 0
    disc_in_channels: 6
    disc_num_layers: 3
  ddconfig:
    double_z: True
    z_channels: 8
    resolution: [96, 96, 96]
    in_channels: 6
    out_ch: 6
    ch: 80
    groups: 1
    ch_mult: [ 1, 2, 4]  # num_down = len(ch_mult)-1
    num_res_blocks: 2
    attn_resolutions: [ ]
    dropout: 0.0
  render_kwargs:
    hwf: [800, 800, 1111.1113654242622]  # default hwf
    near: 2
    far: 4
    ndc: False
    render_factor: 0
    inverse_y: False
    flip_x: False
    flip_y: False
    stepsize: 0.25
    bg: 1
    render_depth: False
    rotate_flag: False
    N_rand: 8192
    inner_iter: 50
    weight_main: 3. # 1 default
    weight_entropy_last: 0.003 # 0.001 default
    weight_rgbper: 0.03 # 0.01 default
    weight_tv: !!float 1e-6
    weight_cls: 0.1
    dvgo:
      xyz_min: [-1, -1, -1]  # default
      xyz_max: [1, 1, 1]
      num_voxels: 262144
      num_voxels_base: 262144
      alpha_init: 0.01
      fast_color_thres: 0.0001
      mask_cache_thres: 0.001
      rgbnet_dim: 4
      viewbase_pe: 4
      rgbnet_direct: True
      rgbnet_full_implicit: False
      rgbnet_depth: 1
      rgbnet_width: 128
  ckpt_path: "/data/huang/diff_nerf/result_ae_kl_d4_96_all/model-15.pt"

data:
  class_name: diff_nerf.data.VolumeDataset
  cls_names: ['04379243', '03001627', '02691156', '02958343', '03636649', '03642806', '03467517', '03948459']
  data_type: 'blender'
  tar_path: '/data/huang/diff_nerf/Vox_96_ShapeNet_v1'
  image_path: '/data/huang/diff_nerf/ShapeNet_v1_Part_Data'
  load_rgb_net: False
  load_mask_cache: False
  use_rotate_transform: False
  batch_size: 2
  white_bkgd: True
  load_render_kwargs: True
  load_mask: False
  sample_num: 1
  normalize: False

trainer:
  gradient_accumulate_every: 2  # not true gradient_accumulate_every, but used for optimize g and d alternately
  lr: !!float 5e-5
  min_lr: 0.2
  train_num_steps: 150000
  save_and_sample_every: 10000
  log_freq: 500
#  results_folder: '/media/huang/T7/data/diff_nerf/result_ae_kl_64x64x64_d4_mlp3_non_normalize_non_cls'
  results_folder: '/data/huang/diff_nerf/result_ae_kl_d4_96_all_6630'
  amp: False
  fp16: False
  resume_milestone: current
  ema_update_after_step: 10000
  ema_update_every: 8