model:
  class_name: diff_nerf.diff_nerf_const_sde_ldm_distill.LatentDiffusion
  ldm: True
  image_size: [ 64, 64, 64 ]
  ckpt_path:
  ignore_keys: [ ]
  only_model: False
  timesteps: 1000
  train_sample: -1
  sampling_timesteps: 20
  loss_type: l2
  use_l1: False
  objective: pred_KC
  start_dist: normal
  perceptual_weight: 0
  scale_by_std: True
  scale_factor: 0.3
  default_scale: True
  scale_by_softsign: False
  eps: !!float 1e-3
  weighting_loss: True
  first_stage:
    class_name: diff_nerf.encoder_decoder_3d_10.AutoencoderKL
    embed_dim: 5
    std_scale: 4
    use_render_loss: True
    use_cls_loss: False
    cls_start: 10000
    cls_path: "/media/huang/T7/data/diff_nerf/classifier/best_model_res18_rotate_non_normalize"
    render_start: 20000
    grid_size: [ 64, 32, 16 ]
    maxm: 191.3546
    minm: -258.9259
    lossconfig:
      disc_start: 80001
      kl_weight: 0.000001
      disc_weight: 0.5
      perceptual_weight: 0
      disc_in_channels: 5
      disc_num_layers: 3
    ddconfig:
      double_z: True
      z_channels: 10
      resolution: [ 64, 64, 64 ]
      in_channels: 5
      out_ch: 5
      ch: 96
      groups: 1
      ch_mult: [ 1, 2, 4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0
    render_kwargs:
      hwf: [ 800, 800, 1111.1113654242622 ]  # default hwf
      near: 2
      far: 4
      ndc: False
      render_factor: 0
      inverse_y: False
      flip_x: False
      flip_y: False
      stepsize: 0.25
      bg: 1
      render_depth: False
      rotate_flag: False
      maskcache_sampling: True
      N_rand: 8192
      inner_iter: 10
      weight_main: 3. # 1 default
      weight_entropy_last: 0.003 # 0.001 default
      weight_rgbper: 0.03 # 0.01 default
      weight_tv: !!float 1e-6
      weight_cls: 0.1
      dvgo:
        xyz_min: [ -1, -1, -1 ]  # default
        xyz_max: [ 1, 1, 1 ]
        num_voxels: 262144
        num_voxels_base: 262144
        alpha_init: 0.01
        fast_color_thres: 0.0001
        mask_cache_thres: 0.001
        rgbnet_dim: 4
        viewbase_pe: 4
        rgbnet_direct: True
        rgbnet_full_implicit: False
        rgbnet_depth: 8
        rgbnet_width: 128
    ckpt_path: '/data/huang/diff_nerf/result_ae_kl_64x64x64_ae3d10_bed/model-15.pt'
    # ckpt_path: '/media/huang/ZX3 512G/data/diff_nerf/result_ae_kl_128x128x128_d4/model-20.pt'
  unet:
    class_name: diff_nerf.uncond_3dunet_sb.Unet3D
    dim: 96
    dim_mults: [1, 2, 4]
    channels: 5
    resnet_block_groups: 6
    heads: 4
    learned_sinusoidal_dim: 16
    window_size_q: [[8, 8, 8], [4, 4, 4], [2, 2, 2], [2, 2, 2]]
    window_size_k: [[[8, 8, 8], [4, 4, 4], [2, 2, 2]],
                    [[4, 4, 4], [2, 2, 2]],
                    [[2, 2, 2], [1, 1, 1]],
                    [[2, 2, 2], [1, 1, 1]]]
    out_mul: 1

data:
  class_name: diff_nerf.data.VolumeDataset
  data_type: 'blender'
  cls_names: [ '02818832' ]
  tar_path: '/data/huang/diff_nerf/DVGO_results_64x64x64'
  image_path: '/data/huang/diff_nerf/ShapeNet_Render'
  load_rgb_net: False
  load_mask_cache: False
  use_rotate_transform: False
  batch_size: 2
  white_bkgd: True
  load_render_kwargs: True
  sample_num: 5
  normalize: False
  maxm: 191.3546
  minm: -258.9259

trainer:
  gradient_accumulate_every: 8  # not true gradient_accumulate_every, but used for optimize g and d alternately
  lr: !!float 5e-5
  min_lr: !!float 1e-5
  train_wd: !!float 1e-2
  train_num_steps: 200000
  save_and_sample_every: 10000
  log_freq: 500
  results_folder: '/data/huang/diff_nerf/result_uncond_const_sde_64x64x64_ae3d10_bed'
  amp: False
  fp16: False
  test_before: True
  resume_milestone: current
  ema_update_after_step: 10000
  ema_update_every: 10